-- The development tenant.
--
-- This script cannot seed it: init scripts run when the PostgreSQL volume is first created,
-- before any service has started, so the `tenants` tables Flyway owns do not exist yet.
--
-- Seeding is done by each service's DevTenantSeeder at startup instead — compose sets
-- LEDGER_DEV_TENANT_ID, FINCORE_CORE_DEV_TENANT_ID and FINCORE_NOTIFICATION_DEV_TENANT_ID to
-- 00000000-0000-4000-8000-000000000001, each service registers it in its own registry and
-- announces having done so. A deployment must never set those variables; real provisioning
-- belongs to the control plane when it exists.
SELECT 'dev tenant is seeded by each service at startup (DevTenantSeeder); see compose.yaml' AS note;
